# Generated by Django 4.1.5 on 2023-04-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_travel_agency_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('content', models.TextField(blank=True, verbose_name='Анықтама')),
                ('captcha', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Сақталған уақыты')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Өзгертілген уақыты')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Байланыс',
                'verbose_name_plural': 'Байланыстар',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
